name: graphnet
channels:
 - pytorch
 - conda-forge
dependencies:
  - pytorch
  - torchvision
  - cpuonly
  - nibabel=2.2.1
  - nilearn=0.4.0
  - pandas=0.21.0
  - scikit-learn=0.21.3
  - scipy=1.0.0
  - seaborn=0.8.1
  pip:
    - torch-cluster==1.3.0
    - torch-geometric==1.2.0
    - torch-scatter==1.2.0
    - torch-sparse==0.4.0
