name: graphnet
channels:
 - pytorch
 - conda-forge
dependencies:
  - pytorch==1.8.1
  - torchvision==0.9.1
  - cpuonly
  - nilearn==0.7.1
  - pandas==1.2.4
  - scikit-learn==0.24.2
  - scipy==1.6.3
  - pip=19.3.1 
  - pip:
    - torch-cluster==1.5.9
    - torch-geometric==1.7.0
    - torch-scatter==2.0.6
    - torch-sparse==0.6.9
    - lmdb==1.2.1
    - tensorpack==0.11
