name: graphnet
dependencies:
  - pip=9.0.3
  - pip:
    - matplotlib==2.1.2
    - nibabel==2.2.1
    - nilearn==0.4.0
    - numpy==1.14.1
    - pandas
    - scikit-learn==0.21.3
    - scipy==1.0.0
    - seaborn==0.8.1
    - torch==1.3.1+cpu
    - torchvision==0.4.2+cpu
    - -f https://download.pytorch.org/whl/torch_stable.html
