name: graphnet
channels:
 - pytorch
 - conda-forge
dependencies:
  - pytorch
  - torchvision
  - cpuonly
  - numpy
  - nibabel
  - nilearn
  - pandas
  - scikit-learn
  - scipy
  - seaborn
  - pip=19.3.1 
  - pip:
    - torch-cluster==1.3.0
    - torch-geometric==1.2.0
    - torch-scatter==1.2.0
    - torch-sparse==0.4.0
